/**
 * Remote window overlay 样式表（client.remote_window_overlay）。
 */
import type { CSSProperties } from 'react';
import { REMOTE_WINDOW_FLOATING_BOTTOM_BASE_PX } from './remote-window-overlay-constants';

export const styles: Record<string, CSSProperties> = {
  compositeStrip: {
    position: 'absolute',
    left: 8,
    right: 8,
    top: 8,
    zIndex: 60,
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
    pointerEvents: 'auto',
    borderRadius: 10,
    background: 'rgba(10, 14, 20, 0.72)',
    backdropFilter: 'blur(6px)',
    padding: 8,
  },
  compositeThumbRow: {
    display: 'flex',
    flexDirection: 'row',
    gap: 8,
    overflowX: 'auto',
    overflowY: 'hidden',
    WebkitOverflowScrolling: 'touch',
    scrollbarWidth: 'thin',
  },
  compositeThumbButton: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 2,
    padding: 3,
    border: '1px solid rgba(255,255,255,0.14)',
    borderRadius: 8,
    background: 'rgba(255,255,255,0.05)',
    cursor: 'pointer',
    flexShrink: 0,
  },
  compositeThumbButtonFocused: {
    border: '2px solid #55b6ff',
    padding: 2,
  },
  compositeThumbCanvas: {
    display: 'block',
    width: '100%',
    borderRadius: 4,
    background: '#0a0e14',
  },
  compositeThumbLabel: {
    fontSize: 10,
    color: 'rgba(255,255,255,0.7)',
    lineHeight: '12px',
  },
  entryButton: {
    position: 'fixed',
    right: 14,
    zIndex: 44,
    width: 48,
    height: 48,
    borderRadius: 14,
    border: '1px solid rgba(255,255,255,0.12)',
    background: 'rgba(15, 23, 38, 0.9)',
    color: 'var(--zterm-panel-accent)',
    fontWeight: 900,
    fontSize: 16,
    boxShadow: '0 12px 24px rgba(0,0,0,0.28)',
    backdropFilter: 'blur(10px)',
    touchAction: 'none',
    userSelect: 'none',
    WebkitUserSelect: 'none',
    cursor: 'grab',
  },
  browserEntryButton: {
    color: '#8fd3ff',
    fontSize: 12,
  },
  pickerPanel: {
    position: 'absolute',
    left: 12,
    right: 12,
    top: 'calc(env(safe-area-inset-top, 0px) + 58px)',
    maxHeight: 'min(70vh, 560px)',
    zIndex: 31,
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    borderRadius: 16,
    border: '1px solid rgba(151, 164, 186, 0.22)',
    background: 'rgba(13, 19, 31, 0.96)',
    color: '#edf4ff',
    boxShadow: '0 24px 60px rgba(0,0,0,0.42)',
    backdropFilter: 'blur(14px)',
  },
  panelHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    gap: 10,
    padding: '14px 14px 10px',
    borderBottom: '1px solid rgba(151, 164, 186, 0.16)',
  },
  panelTitle: {
    fontSize: 15,
    fontWeight: 900,
    letterSpacing: 0,
  },
  panelSubtitle: {
    marginTop: 3,
    fontSize: 12,
    color: 'rgba(237,244,255,0.62)',
  },
  panelActions: {
    display: 'flex',
    gap: 8,
    alignItems: 'flex-start',
  },
  headerButton: {
    minHeight: 48,
    padding: '0 12px',
    borderRadius: 10,
    border: '1px solid rgba(151, 164, 186, 0.18)',
    background: 'rgba(36, 48, 72, 0.84)',
    color: '#edf4ff',
    fontWeight: 850,
  },
  headerIconButton: {
    flex: '0 0 auto',
    width: 48,
    height: 48,
    borderRadius: 10,
    border: '1px solid rgba(151, 164, 186, 0.18)',
    background: 'rgba(36, 48, 72, 0.84)',
    color: '#edf4ff',
    fontWeight: 900,
  },
  headerIconButtonBusy: {
    opacity: 0.78,
    background: 'rgba(31, 214, 122, 0.18)',
    border: '1px solid rgba(31, 214, 122, 0.42)',
  },
  headerModeButton: {
    flex: '0 0 auto',
    minWidth: 48,
    minHeight: 48,
    padding: '0 8px',
    borderRadius: 10,
    border: '1px solid rgba(151, 164, 186, 0.18)',
    background: 'rgba(36, 48, 72, 0.84)',
    color: '#edf4ff',
    fontSize: 12,
    fontWeight: 900,
  },
  headerModeButtonActive: {
    flex: '0 0 auto',
    minWidth: 48,
    minHeight: 48,
    padding: '0 8px',
    borderRadius: 10,
    border: '1px solid rgba(31, 214, 122, 0.42)',
    background: 'rgba(31, 214, 122, 0.18)',
    color: '#edf4ff',
    fontSize: 12,
    fontWeight: 900,
  },
  bitrateSelect: {
    flex: '0 0 auto',
    minHeight: 48,
    maxWidth: 108,
    borderRadius: 10,
    border: '1px solid rgba(151, 164, 186, 0.18)',
    background: 'rgba(36, 48, 72, 0.84)',
    color: '#edf4ff',
    fontSize: 12,
    fontWeight: 850,
    outline: 'none',
  },
  touchScrollFractionSelect: {
    flex: '0 0 auto',
    minHeight: 48,
    maxWidth: 92,
    borderRadius: 10,
    border: '1px solid rgba(151, 164, 186, 0.18)',
    background: 'rgba(36, 48, 72, 0.84)',
    color: '#edf4ff',
    fontSize: 12,
    fontWeight: 850,
    outline: 'none',
  },
  screenshotToast: {
    position: 'absolute',
    left: '50%',
    top: 12,
    zIndex: 5,
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    width: 'max-content',
    maxWidth: 'calc(100% - 24px)',
    minHeight: 38,
    padding: '8px 12px',
    borderRadius: 12,
    color: '#edf4ff',
    background: 'rgba(6, 12, 22, 0.9)',
    border: '1px solid rgba(151, 164, 186, 0.2)',
    boxShadow: '0 14px 36px rgba(0,0,0,0.38)',
    backdropFilter: 'blur(12px)',
    pointerEvents: 'none',
    animation: 'zterm-remote-window-shot-pop 160ms ease-out both',
  },
  screenshotToastProgress: {
    border: '1px solid rgba(31, 214, 122, 0.32)',
  },
  screenshotToastSuccess: {
    border: '1px solid rgba(31, 214, 122, 0.44)',
    animation: 'zterm-remote-window-shot-pop 160ms ease-out both, zterm-remote-window-shot-pulse 1.1s ease-out 1',
  },
  screenshotToastError: {
    border: '1px solid rgba(255, 104, 124, 0.46)',
  },
  screenshotSpinner: {
    flex: '0 0 auto',
    width: 18,
    height: 18,
    borderRadius: 999,
    border: '2px solid rgba(237,244,255,0.22)',
    borderTopColor: 'var(--zterm-panel-accent)',
    animation: 'zterm-remote-window-shot-spin 0.78s linear infinite',
  },
  screenshotResultIcon: {
    flex: '0 0 auto',
    width: 24,
    height: 24,
    borderRadius: 999,
    display: 'grid',
    placeItems: 'center',
    background: 'rgba(31, 214, 122, 0.16)',
    color: 'var(--zterm-panel-accent)',
    fontSize: 10,
    fontWeight: 950,
    lineHeight: 1,
  },
  screenshotResultIconError: {
    background: 'rgba(255, 104, 124, 0.16)',
    color: '#ff7a8d',
  },
  screenshotToastText: {
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: 2,
  },
  screenshotToastTitle: {
    fontSize: 12,
    fontWeight: 900,
    lineHeight: 1.15,
    whiteSpace: 'nowrap',
  },
  screenshotToastDetail: {
    maxWidth: 'min(240px, 62vw)',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    color: 'rgba(237,244,255,0.68)',
    fontSize: 10,
    fontWeight: 750,
    lineHeight: 1.2,
  },
  errorBox: {
    margin: '10px 12px 0',
    padding: '9px 10px',
    borderRadius: 10,
    background: 'rgba(109, 24, 33, 0.82)',
    color: '#ffd7dc',
    fontSize: 12,
    lineHeight: 1.4,
  },
  errorStrip: {
    margin: '10px 12px 0',
    padding: '8px 10px',
    borderRadius: 10,
    background: 'rgba(97, 63, 13, 0.72)',
    color: '#ffe2a8',
    fontSize: 12,
    lineHeight: 1.4,
  },
  targetList: {
    flex: '0 1 auto',
    minHeight: 0,
    maxHeight: 'calc(min(70vh, 560px) - 72px)',
    padding: 10,
    overflowY: 'auto',
    display: 'grid',
    gap: 8,
  },
  targetRow: {
    display: 'grid',
    gridTemplateColumns: '86px minmax(0, 1fr)',
    gap: '4px 10px',
    padding: '10px 11px',
    textAlign: 'left',
    borderRadius: 12,
    border: '1px solid rgba(151, 164, 186, 0.14)',
    background: 'rgba(27, 37, 56, 0.88)',
    color: '#edf4ff',
  },
  targetGroupRow: {
    display: 'grid',
    gridTemplateColumns: '86px minmax(0, 1fr)',
    gap: '4px 10px',
    padding: '10px 11px',
    textAlign: 'left',
    borderRadius: 12,
    border: '1px solid rgba(151, 164, 186, 0.18)',
    background: 'rgba(20, 31, 49, 0.92)',
    color: '#edf4ff',
  },
  targetKind: {
    color: 'var(--zterm-panel-accent)',
    fontSize: 11,
    fontWeight: 900,
    textTransform: 'uppercase',
    letterSpacing: 0,
  },
  targetMain: {
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    fontSize: 13,
    fontWeight: 850,
  },
  targetMeta: {
    gridColumn: '2 / 3',
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    color: 'rgba(237,244,255,0.62)',
    fontSize: 11,
  },
  emptyState: {
    minHeight: 44,
    display: 'grid',
    placeItems: 'center',
    color: 'rgba(237,244,255,0.62)',
    fontSize: 13,
  },
  floatingOverlay: {
    position: 'absolute',
    right: 12,
    bottom: REMOTE_WINDOW_FLOATING_BOTTOM_BASE_PX,
    zIndex: 32,
    width: 'min(78vw, 360px)',
    maxHeight: 'calc(100dvh - 164px - env(safe-area-inset-top, 0px))',
    display: 'flex',
    flexDirection: 'column',
    borderRadius: 16,
    overflow: 'hidden',
    border: '1px solid rgba(151, 164, 186, 0.22)',
    background: '#050910',
    color: '#edf4ff',
    boxShadow: '0 24px 60px rgba(0,0,0,0.46)',
  },
  floatingResizeHandleLeft: {
    position: 'absolute',
    left: 0,
    bottom: 0,
    width: 48,
    height: 48,
    zIndex: 2,
    cursor: 'nesw-resize',
    touchAction: 'none',
    background: 'radial-gradient(circle at bottom left, rgba(31,214,122,0.36), rgba(31,214,122,0) 68%)',
  },
  floatingResizeHandleRight: {
    position: 'absolute',
    right: 0,
    bottom: 0,
    width: 48,
    height: 48,
    zIndex: 2,
    cursor: 'nwse-resize',
    touchAction: 'none',
    background: 'radial-gradient(circle at bottom right, rgba(31,214,122,0.36), rgba(31,214,122,0) 68%)',
  },
  fullscreenOverlay: {
    position: 'fixed',
    inset: 0,
    width: '100%',
    height: '100%',
    minHeight: '100%',
    zIndex: 90,
    display: 'flex',
    flexDirection: 'column',
    boxSizing: 'border-box',
    paddingTop: 'calc(44px + env(safe-area-inset-top, 0px))',
    paddingLeft: 'max(8px, env(safe-area-inset-left, 0px))',
    paddingRight: 'max(8px, env(safe-area-inset-right, 0px))',
    background: '#02050a',
    color: '#edf4ff',
    contain: 'layout paint',
    isolation: 'isolate',
  },
  lockedToolbar: {
    minHeight: 42,
    display: 'flex',
    flexDirection: 'column',
    background: 'rgba(13, 19, 31, 0.94)',
    borderBottom: '1px solid rgba(151, 164, 186, 0.14)',
  },
  lockedTopBar: {
    minHeight: 42,
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 8,
    padding: '7px 8px',
  },
  lockedPrimaryActions: {
    flex: '0 0 auto',
    display: 'flex',
    gap: 6,
  },
  lockedControlStrip: {
    minWidth: 0,
    display: 'flex',
    gap: 6,
    alignItems: 'center',
    justifyContent: 'space-between',
    overflowX: 'hidden',
    overflowY: 'hidden',
    padding: '0 8px 7px',
    WebkitOverflowScrolling: 'touch',
    scrollbarWidth: 'none',
    touchAction: 'manipulation',
  },
  gestureGuide: {
    padding: '0 10px 7px',
    color: 'rgba(237,244,255,0.64)',
    fontSize: 11,
    lineHeight: 1.3,
  },
  lockedTitle: {
    minWidth: 0,
    flex: '1 1 auto',
    display: 'flex',
    gap: 8,
    alignItems: 'center',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    fontSize: 12,
    fontWeight: 850,
  },
  activeAppSwitch: {
    position: 'relative',
    minWidth: 0,
    flex: '1 1 auto',
  },
  activeAppSwitchButton: {
    width: '100%',
    minWidth: 48,
    minHeight: 48,
    display: 'block',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    padding: '3px 2px',
    border: 0,
    background: 'transparent',
    color: '#edf4ff',
    textAlign: 'left',
    fontSize: 12,
    fontWeight: 850,
  },
  appSwitchPopover: {
    position: 'absolute',
    top: 'calc(100% + 8px)',
    left: 0,
    width: 'min(78vw, 340px)',
    maxHeight: 'min(52vh, 420px)',
    overflowY: 'auto',
    display: 'grid',
    gap: 8,
    padding: 8,
    borderRadius: 12,
    border: '1px solid rgba(151, 164, 186, 0.22)',
    background: 'rgba(8, 13, 23, 0.98)',
    boxShadow: '0 18px 46px rgba(0,0,0,0.52)',
    zIndex: 4,
  },
  appSwitchGroup: {
    display: 'grid',
    gap: 5,
  },
  appSwitchGroupTitle: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    padding: '2px 4px',
    color: 'rgba(237,244,255,0.68)',
    fontSize: 10,
    fontWeight: 900,
    textTransform: 'uppercase',
    letterSpacing: 0,
  },
  appSwitchGroupCount: {
    flex: '0 0 auto',
    minWidth: 18,
    padding: '1px 5px',
    borderRadius: 8,
    background: 'rgba(151, 164, 186, 0.14)',
    color: 'var(--zterm-panel-accent)',
    textAlign: 'center',
  },
  appSwitchTargetRow: {
    minWidth: 0,
    display: 'grid',
    gap: 2,
    padding: '8px 9px',
    borderRadius: 9,
    border: '1px solid rgba(151, 164, 186, 0.14)',
    background: 'rgba(22, 32, 50, 0.92)',
    color: '#edf4ff',
    textAlign: 'left',
  },
  appSwitchTargetRowActive: {
    minWidth: 0,
    display: 'grid',
    gap: 2,
    padding: '8px 9px',
    borderRadius: 9,
    border: '1px solid var(--zterm-panel-accent)',
    background: 'rgba(31, 214, 122, 0.12)',
    color: '#edf4ff',
    textAlign: 'left',
  },
  appSwitchTargetTitle: {
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    fontSize: 12,
    fontWeight: 900,
  },
  appSwitchTargetMeta: {
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    color: 'rgba(237,244,255,0.58)',
    fontSize: 10,
    fontWeight: 750,
  },
  appSwitchTargetClose: {
    justifySelf: 'end',
    marginTop: -18,
    padding: '1px 6px',
    borderRadius: 6,
    color: '#ff9a9a',
    background: 'rgba(255, 92, 92, 0.12)',
    fontSize: 12,
    fontWeight: 900,
    cursor: 'pointer',
  },
  targetClose: {
    position: 'absolute',
    right: 10,
    top: 10,
    padding: '1px 6px',
    borderRadius: 6,
    color: '#ff9a9a',
    background: 'rgba(255, 92, 92, 0.12)',
    fontSize: 12,
    fontWeight: 900,
    cursor: 'pointer',
  },
  streamStatusPanel: {
    display: 'grid',
    gap: 3,
    maxHeight: 220,
    overflowY: 'auto',
    padding: '8px 10px',
    borderTop: '1px solid rgba(151, 164, 186, 0.2)',
    background: 'rgba(5, 9, 15, 0.96)',
    color: 'rgba(237,244,255,0.78)',
    fontSize: 12,
    lineHeight: 1.35,
    whiteSpace: 'pre-wrap',
    wordBreak: 'break-word',
  },
  moreField: {
    minHeight: 48,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  debugDiagnostics: {
    marginTop: 4,
    paddingTop: 8,
    borderTop: '1px solid rgba(151, 164, 186, 0.16)',
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace',
    fontSize: 10,
  },
  appSwitchError: {
    padding: '7px 8px',
    borderRadius: 8,
    background: 'rgba(97, 63, 13, 0.72)',
    color: '#ffe2a8',
    fontSize: 11,
    lineHeight: 1.35,
  },
  appSwitchEmpty: {
    padding: 10,
    color: 'rgba(237,244,255,0.58)',
    fontSize: 11,
    textAlign: 'center',
  },
  inputModeBadge: {
    flex: '0 0 auto',
    minWidth: 48,
    minHeight: 48,
    padding: '2px 6px',
    borderRadius: 8,
    border: '1px solid rgba(151, 164, 186, 0.18)',
    color: 'rgba(237,244,255,0.68)',
    fontSize: 11,
    fontWeight: 850,
  },
  lockedActions: {
    display: 'flex',
    gap: 6,
  },
  videoPlaceholder: {
    flex: 1,
    minHeight: 0,
    position: 'relative',
    overflow: 'hidden',
    background: '#0a101b',
    contain: 'paint',
    outline: 'none',
    touchAction: 'none',
  },
  videoContentFrame: {
    position: 'absolute',
    display: 'grid',
    placeItems: 'center',
    overflow: 'hidden',
    background: '#0a101b',
    pointerEvents: 'none',
  },
  videoContentFallback: {
    position: 'absolute',
    inset: 0,
    display: 'grid',
    placeItems: 'center',
    overflow: 'hidden',
    background: '#0a101b',
    pointerEvents: 'none',
  },
  canvasFocusHits: {
    position: 'absolute',
    inset: 0,
    zIndex: 30,
    pointerEvents: 'none',
  },
  canvasFocusHit: {
    position: 'absolute',
    pointerEvents: 'auto',
    border: '1px solid rgba(85,182,255,0.24)',
    borderRadius: 4,
    background: 'transparent',
    touchAction: 'none',
    cursor: 'pointer',
  },
  videoFrame: {
    position: 'relative',
    width: '100%',
    height: '100%',
    display: 'grid',
    placeItems: 'center',
    alignContent: 'center',
    gap: 8,
    border: '1px solid rgba(151, 164, 186, 0.12)',
    background: '#0a101b',
    contain: 'paint',
    overflow: 'hidden',
  },
  videoElement: {
    width: '100%',
    height: '100%',
    display: 'block',
    objectFit: 'contain',
    background: 'transparent',
    pointerEvents: 'none',
    position: 'relative',
    zIndex: 1,
    transition: 'opacity 120ms ease-out',
  },
  videoError: {
    borderColor: 'rgba(248, 113, 113, 0.34)',
    background: '#170d14',
  },
  videoStatus: {
    position: 'relative',
    zIndex: 1,
    fontSize: 14,
    fontWeight: 900,
    color: '#edf4ff',
  },
  videoMeta: {
    position: 'relative',
    zIndex: 1,
    maxWidth: '90%',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    fontSize: 11,
    color: 'rgba(237,244,255,0.62)',
  },
  videoWallpaper: {
    position: 'absolute',
    inset: 0,
    zIndex: 2,
    display: 'grid',
    placeItems: 'center',
    background: '#0a101b',
    boxShadow: 'inset 0 0 0 1px rgba(237,244,255,0.04), inset 0 18px 48px rgba(255,255,255,0.035), inset 0 -36px 80px rgba(0,0,0,0.38)',
    pointerEvents: 'none',
    isolation: 'isolate',
  },
  videoWallpaperLogo: {
    width: 'min(42%, 156px)',
    maxHeight: '42%',
    objectFit: 'contain',
    opacity: 0.62,
  },
  videoWindowGroupFloating: {
    flex: '0 0 auto',
    minWidth: 0,
    minHeight: 0,
    padding: 8,
    background: '#0a101b',
    overflow: 'hidden',
    boxSizing: 'border-box',
  },
  videoWindowGroupFullscreen: {
    flex: 1,
    minWidth: 0,
    minHeight: 0,
    padding: 8,
    background: '#0a101b',
    overflow: 'hidden',
    boxSizing: 'border-box',
  },
  videoWindowGroupTile: {
    position: 'relative',
    width: '100%',
    height: '100%',
    minHeight: 58,
    display: 'grid',
    gridTemplateRows: 'minmax(34px, 1fr)',
    padding: 4,
    borderRadius: 8,
    border: '1px solid rgba(151, 164, 186, 0.18)',
    background: 'rgba(20, 31, 49, 0.88)',
    color: '#edf4ff',
    boxSizing: 'border-box',
  },
  videoWindowGroupCloseButton: {
    position: 'absolute',
    top: 6,
    right: 6,
    zIndex: 2,
    width: 24,
    height: 24,
    borderRadius: 8,
    border: '1px solid rgba(151, 164, 186, 0.28)',
    background: 'rgba(5, 9, 16, 0.78)',
    color: '#edf4ff',
    fontSize: 12,
    fontWeight: 950,
    lineHeight: 1,
  },
  videoWindowGroupThumb: {
    minWidth: 0,
    minHeight: 48,
    display: 'grid',
    placeItems: 'center',
    overflow: 'hidden',
    borderRadius: 7,
    background: '#050910',
    boxShadow: 'inset 0 0 0 1px rgba(237,244,255,0.08)',
  },
  videoWindowGroupThumbImage: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    display: 'block',
  },
  videoWindowGroupThumbTitle: {
    maxWidth: '86%',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    color: 'rgba(237,244,255,0.7)',
    fontSize: 10,
    fontWeight: 900,
  },
  streamFeedbackToast: {
    position: 'absolute',
    left: 12,
    right: 12,
    bottom: 12,
    zIndex: 5,
    display: 'grid',
    gap: 2,
    padding: '8px 10px',
    borderRadius: 12,
    border: '1px solid rgba(255, 198, 92, 0.42)',
    background: 'rgba(48, 31, 9, 0.9)',
    color: '#ffe2a8',
    boxShadow: '0 14px 36px rgba(0,0,0,0.36)',
    pointerEvents: 'none',
  },
};
