import type { Dispatch, SetStateAction } from 'react';

export interface TerminalSessionDrawerNewSessionDraft { hostKey?: string; sessionName: string; cwd: string; terminalBackend: 'tmux' | 'herdr'; }
interface Props { draft: TerminalSessionDrawerNewSessionDraft; setDraft: Dispatch<SetStateAction<TerminalSessionDrawerNewSessionDraft | null>>; onCancel: () => void; onConfirm: () => void; }

export function TerminalSessionDrawerNewSessionDialog({ draft, setDraft, onCancel, onConfirm }: Props) {
  return <div data-testid="terminal-session-drawer-new-session-dialog" style={{ margin: '8px 10px', padding: '12px', borderRadius: '16px', border: '1px solid var(--zterm-panel-border)', background: 'var(--zterm-panel-bg)', boxShadow: '0 14px 30px var(--zterm-panel-shadow)', display: 'flex', flexDirection: 'column', gap: '10px' }}>
    <div style={{ color: 'var(--zterm-panel-text)', fontSize: '13px', fontWeight: 850 }}>新建 Session</div>
    <label style={{ display: 'flex', flexDirection: 'column', gap: '5px', color: 'var(--zterm-panel-muted)', fontSize: '11px', fontWeight: 800 }}>名称<input aria-label="新 session 名称" value={draft.sessionName} onChange={(event) => setDraft((current) => current ? { ...current, sessionName: event.target.value } : current)} style={{ height: '34px', borderRadius: '10px', border: '1px solid var(--zterm-panel-border)', background: 'var(--zterm-panel-surface)', color: 'var(--zterm-panel-text)', padding: '0 10px', fontSize: '13px' }} /></label>
    <label style={{ display: 'flex', flexDirection: 'column', gap: '5px', color: 'var(--zterm-panel-muted)', fontSize: '11px', fontWeight: 800 }}>启动路径<input aria-label="新 session 启动路径" value={draft.cwd} placeholder="~/" onChange={(event) => setDraft((current) => current ? { ...current, cwd: event.target.value } : current)} style={{ height: '34px', borderRadius: '10px', border: '1px solid var(--zterm-panel-border)', background: 'var(--zterm-panel-surface)', color: 'var(--zterm-panel-text)', padding: '0 10px', fontSize: '13px' }} /></label>
    <div aria-label="新 session backend" style={{ display: 'flex', gap: '6px' }}>{(['tmux', 'herdr'] as const).map((backend) => <button key={backend} type="button" aria-pressed={draft.terminalBackend === backend} onClick={() => setDraft((current) => current ? { ...current, terminalBackend: backend } : current)} style={{ flex: 1, height: '34px', borderRadius: '10px', border: '1px solid var(--zterm-panel-border)', background: draft.terminalBackend === backend ? 'var(--zterm-panel-active)' : 'var(--zterm-panel-surface)', color: draft.terminalBackend === backend ? 'var(--zterm-panel-accent)' : 'var(--zterm-panel-muted)', fontWeight: 850 }}>{backend === 'tmux' ? 'tmux' : 'Herdr'}</button>)}</div>
    <div style={{ display: 'flex', gap: '8px' }}><button type="button" onClick={onCancel} style={{ flex: 1, height: '34px', borderRadius: '10px', border: '1px solid var(--zterm-panel-border)', background: 'var(--zterm-panel-surface)', color: 'var(--zterm-panel-muted)', fontWeight: 800 }}>取消</button><button type="button" disabled={!draft.sessionName.trim()} onClick={onConfirm} style={{ flex: 1, height: '34px', borderRadius: '10px', border: '1px solid var(--zterm-panel-border)', background: draft.sessionName.trim() ? 'var(--zterm-panel-active)' : 'var(--zterm-panel-surface)', color: draft.sessionName.trim() ? 'var(--zterm-panel-accent)' : 'var(--zterm-panel-muted)', fontWeight: 900 }}>创建</button></div>
  </div>;
}
