import { useMemo } from 'react';
import {
  resolveTerminalRefreshCadence,
} from '../lib/mobile-config';
import { runtimeDebug } from '../lib/runtime-debug';
import type { TerminalBufferPayload } from '../lib/types';
import {
  createSessionMessageOrchestrationRuntime,
} from './session-context-message-orchestration-runtime';
import {
  createSessionInfraFacadeRuntime,
} from './session-context-infra-facade-runtime';
import {
  createSessionTransportOrchestrationRuntime,
} from './session-context-transport-orchestration-runtime';
import {
  reduceSessionAction,
} from './session-context-core';
import type {
  SessionProviderAssembliesSharedOptions,
  SessionProviderCoreAssembliesResult,
} from './session-context-provider-assembly-types';

const SESSION_HANDSHAKE_TIMEOUT_MS = 4000;
const CLIENT_PING_INTERVAL_MS = 30000;
const ACTIVE_TRANSPORT_STALE_ACTIVITY_MS = CLIENT_PING_INTERVAL_MS + 5000;
const DEFAULT_TERMINAL_SESSION_VIEWPORT = {
  cols: 80,
  rows: 24,
} as const;

function summarizeBufferPayload(payload: TerminalBufferPayload) {
  const firstLine = payload.lines[0];
  const lastLine = payload.lines[payload.lines.length - 1];
  return {
    revision: payload.revision,
    startIndex: payload.startIndex,
    endIndex: payload.endIndex,
    cols: payload.cols,
    rows: payload.rows,
    lineCount: payload.lines.length,
    cursor: payload.cursor
      ? {
          rowIndex: payload.cursor.rowIndex,
          col: payload.cursor.col,
          visible: payload.cursor.visible,
        }
      : null,
    firstLineIndex: firstLine ? ('i' in firstLine ? firstLine.i : firstLine.index) : null,
    lastLineIndex: lastLine ? ('i' in lastLine ? lastLine.i : lastLine.index) : null,
  };
}

export function useSessionProviderCoreAssemblies(
  options: SessionProviderAssembliesSharedOptions,
): SessionProviderCoreAssembliesResult {
  const {
    sessionDebugMetricsStoreRef,
    transportRuntimeStoreRef,
    sessionBufferStoreRef,
    sessionRenderGateRef,
    sessionHeadStoreRef,
    pingIntervalsRef,
    handshakeTimeoutsRef,
    sessionVisibleRangeRef,
    lastPongAtRef,
    lastServerActivityAtRef,
    staleTransportProbeAtRef,
    reconnectRuntimesRef,
    manualCloseRef,
    sessionBufferHeadsRef,
    sessionRevisionResetRef,
    pendingInputTailRefreshRef,
    pendingConnectTailRefreshRef,
    pendingResumeTailRefreshRef,
    lastHeadRequestAtRef,
    sessionPullStateRef,
    sessionAttachTokensRef,
    pendingSessionTransportOpenIntentsRef,
    fileTransferMessageRuntimeRef,
    handleSocketConnectedBaselineRef,
    finalizeSocketFailureBaselineRef,
    flushPendingInputQueueRef,
    handleSocketServerMessageRef,
  } = options.refs;

  const sessionInfraRuntime = useMemo(() => createSessionInfraFacadeRuntime({
    stateRef: options.stateRef,
    dispatch: options.dispatch,
    reduceSessionAction,
    transportRuntimeStoreRef,
    sessionBufferStoreRef,
    sessionRenderGateRef,
    sessionHeadStoreRef,
    sessionDebugMetricsStoreRef,
    scheduleStatesRef: options.scheduleStatesRef,
    setScheduleStates: options.setScheduleStates,
    sessionAttachTokensRef,
    pendingSessionTransportOpenIntentsRef,
    reconnectRuntimesRef,
    pendingInputTailRefreshRef,
    pendingConnectTailRefreshRef,
    pendingResumeTailRefreshRef,
    sessionPullStateRef,
    lastServerActivityAtRef,
    staleTransportProbeAtRef,
    lastPongAtRef,
    pingIntervalsRef,
    handshakeTimeoutsRef,
    sessionBufferHeadsRef,
    sessionRevisionResetRef,
    lastHeadRequestAtRef,
    terminalCacheLines: options.terminalCacheLines,
    defaultRows: DEFAULT_TERMINAL_SESSION_VIEWPORT.rows,
    bridgeSettings: options.bridgeSettings,
    wsUrl: options.wsUrl,
    staleActivityMs: ACTIVE_TRANSPORT_STALE_ACTIVITY_MS,
    runtimeDebug,
  }), [options.bridgeSettings, options.dispatch, options.scheduleStatesRef, options.setScheduleStates, options.stateRef, options.terminalCacheLines, options.wsUrl]);

  const {
    readSessionBufferSnapshot,
    updateSessionSync,
    setActiveSessionSync,
    setLiveSessionIdsSync,
    createSessionSync,
    deleteSessionSync,
    moveSessionSync,
    setSessionTitleSync,
    incrementConnectedSync,
    readSessionTransportSocket,
    readSessionTransportHost,
    readSessionTransportRuntime,
    readSessionTargetRuntime,
    readSessionTargetKey,
    readSessionTargetControlSocket,
    writeSessionTransportHost,
    writeSessionTransportSocket,
    writeSessionTargetControlSocket,
    moveSessionTransportSocketAside,
    clearSessionTransportRuntime,
    drainSessionSupersededSockets,
    readSessionTransportToken,
    writeSessionTransportToken,
    isSessionTransportActive,
    hasPendingSessionTransportOpen,
    isPendingSessionTransportOpenStale,
    isReconnectInFlight,
    resolveSessionCacheLines,
    getSessionRenderBufferSnapshot,
    getSessionBufferStore,
    getSessionRenderBufferStore,
    getSessionHeadStore,
    recordSessionRx,
    recordSessionRxBytesOnly,
    scheduleSessionRenderCommit,
    markPendingInputTailRefresh,
    clearSessionPullState,
    settleSessionPullState,
    resetSessionTransportPullBookkeeping,
    isSessionTransportActivityStale,
    sendSocketPayload,
    buildTraversalSocketForHost,
    applyTransportDiagnostics,
    flushRuntimeDebugLogs,
    setScheduleStateForSession,
    clearHeartbeat,
    clearSessionHandshakeTimeout,
    setSessionHandshakeTimeout,
    clearTailRefreshRuntime,
    startSocketHeartbeat,
  } = sessionInfraRuntime;

  const {
    cleanupControlSocket,
    clearReconnectForSession,
    cleanupSocket,
    scheduleReconnect,
    queueConnectTransportOpenIntent,
  } = useMemo(() => createSessionTransportOrchestrationRuntime({
    stateRef: options.stateRef,
    runtimeDebug,
    sessionHandshakeTimeoutMs: SESSION_HANDSHAKE_TIMEOUT_MS,
    refs: {
      pendingSessionTransportOpenIntentsRef,
      reconnectRuntimesRef,
      manualCloseRef,
      lastPongAtRef,
      staleTransportProbeAtRef,
      sessionDebugMetricsStoreRef,
      flushPendingInputQueueRef,
      handleSocketServerMessageRef,
      handleSocketConnectedBaselineRef,
      finalizeSocketFailureBaselineRef,
    },
    readSessionTargetControlSocket,
    readSessionTargetRuntime,
    readSessionTargetKey,
    readSessionTransportSocket,
    readSessionTransportToken,
    readSessionTransportHost,
    writeSessionTransportToken,
    writeSessionTargetControlSocket,
    writeSessionTransportSocket,
    moveSessionTransportSocketAside,
    drainSessionSupersededSockets,
    updateSessionSync,
    clearHeartbeat,
    clearSessionHandshakeTimeout,
    setSessionHandshakeTimeout,
    clearTailRefreshRuntime,
    clearSessionPullState,
    sendSocketPayload,
    buildTraversalSocketForHost,
    applyTransportDiagnostics,
    recordSessionRx,
    recordControlTransportRxBytes: recordSessionRxBytesOnly,
    flushRuntimeDebugLogs,
    startSocketHeartbeat,
    setScheduleStateForSession,
  }), [
    applyTransportDiagnostics,
    buildTraversalSocketForHost,
    clearHeartbeat,
    clearSessionHandshakeTimeout,
    clearSessionPullState,
    clearTailRefreshRuntime,
    drainSessionSupersededSockets,
    flushRuntimeDebugLogs,
    moveSessionTransportSocketAside,
    options.bridgeSettings.terminalWidthMode,
    options.stateRef,
    readSessionTargetControlSocket,
    readSessionTargetKey,
    readSessionTargetRuntime,
    readSessionTransportHost,
    readSessionTransportSocket,
    readSessionTransportToken,
    recordSessionRxBytesOnly,
    sendSocketPayload,
    setScheduleStateForSession,
    setSessionHandshakeTimeout,
    startSocketHeartbeat,
    updateSessionSync,
    writeSessionTargetControlSocket,
    writeSessionTransportSocket,
    writeSessionTransportToken,
  ]);

  const sessionMessageRuntime = useMemo(() => createSessionMessageOrchestrationRuntime({
    refs: {
      stateRef: options.stateRef,
      scheduleStatesRef: options.scheduleStatesRef,
      lastHeadRequestAtRef,
      lastPongAtRef,
      sessionVisibleRangeRef,
      sessionBufferHeadsRef,
      sessionPullStateRef,
      pendingInputTailRefreshRef,
      pendingConnectTailRefreshRef,
      pendingResumeTailRefreshRef,
      sessionRevisionResetRef,
      sessionBufferStoreRef,
      sessionHeadStoreRef,
      sessionDebugMetricsStoreRef,
      pendingSessionTransportOpenIntentsRef,
      manualCloseRef,
    },
    readSessionTransportSocket,
    readSessionBufferSnapshot,
    clearSessionPullState,
    sendSocketPayload,
    resolveTerminalRefreshCadence,
    resolveSessionCacheLines,
    summarizeBufferPayload,
    runtimeDebug,
    isSessionTransportActive,
    scheduleSessionRenderCommit,
    settleSessionPullState,
    setScheduleStateForSession,
    setSessionTitleSync,
    fileTransferMessageRuntime: fileTransferMessageRuntimeRef.current,
    applyTransportDiagnostics,
    updateSessionSync,
    incrementConnectedSync,
    cleanupSocket,
    writeSessionTransportToken,
  }), [
    applyTransportDiagnostics,
    cleanupSocket,
    clearSessionPullState,
    incrementConnectedSync,
    isSessionTransportActive,
    readSessionBufferSnapshot,
    readSessionTransportSocket,
    resolveSessionCacheLines,
    scheduleSessionRenderCommit,
    sendSocketPayload,
    setScheduleStateForSession,
    settleSessionPullState,
    setSessionTitleSync,
    updateSessionSync,
    writeSessionTransportToken,
  ]);

  const {
    requestSessionBufferSync,
    requestSessionBufferHead,
    handleSocketServerMessage,
    handleSocketConnectedBaseline,
    finalizeSocketFailureBaseline,
  } = sessionMessageRuntime;
  handleSocketServerMessageRef.current = handleSocketServerMessage;
  handleSocketConnectedBaselineRef.current = handleSocketConnectedBaseline;
  finalizeSocketFailureBaselineRef.current = finalizeSocketFailureBaseline;

  return useMemo(() => ({
    getSessionRenderBufferSnapshot,
    getSessionBufferStore,
    getSessionRenderBufferStore,
    getSessionHeadStore,
    flushRuntimeDebugLogs,
    clearReconnectForSession,
    writeSessionTransportHost,
    writeSessionTransportToken,
    scheduleReconnect,
    readSessionBufferSnapshot,
    setActiveSessionSync,
    setLiveSessionIdsSync,
    createSessionSync,
    deleteSessionSync,
    moveSessionSync,
    updateSessionSync,
    setSessionTitleSync,
    isSessionTransportActive,
    hasPendingSessionTransportOpen,
    isPendingSessionTransportOpenStale,
    isReconnectInFlight,
    resolveSessionCacheLines,
    scheduleSessionRenderCommit,
    markPendingInputTailRefresh,
    resetSessionTransportPullBookkeeping,
    isSessionTransportActivityStale,
    sendSocketPayload,
    setScheduleStateForSession,
    clearSessionHandshakeTimeout,
    cleanupControlSocket,
    cleanupSocket,
    queueConnectTransportOpenIntent,
    readSessionTransportSocket,
    readSessionTransportHost,
    readSessionTransportRuntime,
    readSessionTargetRuntime,
    readSessionTargetKey,
    clearSessionTransportRuntime,
    requestSessionBufferSync,
    requestSessionBufferHead,
    resolveTerminalRefreshCadence,
  }), [
    clearReconnectForSession,
    clearSessionHandshakeTimeout,
    cleanupControlSocket,
    cleanupSocket,
    createSessionSync,
    deleteSessionSync,
    flushRuntimeDebugLogs,
    getSessionBufferStore,
    getSessionHeadStore,
    getSessionRenderBufferSnapshot,
    getSessionRenderBufferStore,
    hasPendingSessionTransportOpen,
    isPendingSessionTransportOpenStale,
    isReconnectInFlight,
    isSessionTransportActive,
    isSessionTransportActivityStale,
    markPendingInputTailRefresh,
    moveSessionSync,
    queueConnectTransportOpenIntent,
    readSessionBufferSnapshot,
    readSessionTargetKey,
    readSessionTargetRuntime,
    readSessionTransportHost,
    readSessionTransportRuntime,
    readSessionTransportSocket,
    requestSessionBufferHead,
    requestSessionBufferSync,
    resetSessionTransportPullBookkeeping,
    resolveSessionCacheLines,
    resolveTerminalRefreshCadence,
    scheduleReconnect,
    scheduleSessionRenderCommit,
    sendSocketPayload,
    setActiveSessionSync,
    setScheduleStateForSession,
    setSessionTitleSync,
    updateSessionSync,
    writeSessionTransportHost,
    writeSessionTransportToken,
  ]);
}
