import { useCallback, useMemo } from "react";
import { runtimeDebug } from "../lib/runtime-debug";
import { resolveTerminalRefreshCadence } from "../lib/mobile-config";
import { resolveSessionRuntimeTransportCadenceInput } from "../lib/session-runtime-cadence";
import {
  createSessionInfraFacadeRuntime,
} from "./session-context-infra-facade-runtime";
import {
  createSessionTransportOrchestrationRuntime,
} from "./session-context-transport-orchestration-runtime";
import {
  reduceSessionAction,
} from "./session-context-core";
import {
  createSessionMessageAssemblies,
  type SessionMessageAssembliesResult,
} from "./session-context-message-assemblies";
import {
  settleSessionTmuxTargetRequestRuntime,
} from './session-context-tmux-management-runtime';
import type {
  SessionProviderAssembliesSharedOptions,
  SessionProviderCoreAssembliesResult,
} from "./session-context-provider-assembly-types";


const SESSION_HANDSHAKE_TIMEOUT_MS = 4000;
const SESSION_TERMINAL_READY_TIMEOUT_MS = 10000;
const ACTIVE_TRANSPORT_STALE_ACTIVITY_MS = 2500;
const DEFAULT_TERMINAL_SESSION_VIEWPORT = {
  cols: 80,
  rows: 24,
} as const;

export function useSessionProviderCoreAssemblies(
  options: SessionProviderAssembliesSharedOptions,
): SessionProviderCoreAssembliesResult {
  const {
    sessionDebugMetricsStoreRef,
    transportRuntimeStoreRef,
    sessionBufferStoreRef,
    sessionRenderGateRef,
    sessionHeadStoreRef,
    pingIntervalsRef,
    handshakeTimeoutsRef,
    sessionVisibleRangeRef,
    lastPongAtRef,
    lastServerActivityAtRef,
    lastTerminalActivityAtRef,
    staleTransportProbeAtRef,
    reconnectRuntimesRef,
    manualCloseRef,
    sessionBufferHeadsRef,
    sessionRevisionResetRef,
    pendingInputTailRefreshRef,
    pendingConnectTailRefreshRef,
    pendingResumeTailRefreshRef,
    lastConnectedBaselineAtRef,
    connectedBaselineBurstGuardRef,
    lastHeadRequestAtRef,
    lastSyncRequestAtRef,
    sessionPullStateRef,
    sessionAttachTokensRef,
    pendingSessionTransportOpenIntentsRef,
    tmuxTargetRequestsRef,
    activeBodySubscriptionSuppressedRef,
    fileTransferMessageRuntimeRef,
    remoteWindowMessageRuntimeRef,
    handleSocketConnectedBaselineRef,
    finalizeSocketFailureBaselineRef,
    handleSocketServerMessageRef,
  } = options.refs;

  const resolveSessionTerminalRefreshCadence = useCallback((sessionId?: string | null) => resolveTerminalRefreshCadence({
    runtimeTransport: sessionId
      ? resolveSessionRuntimeTransportCadenceInput({
          socket: transportRuntimeStoreRef.current.sessions.get(sessionId)?.activeSocket || null,
          metrics: sessionDebugMetricsStoreRef.current.getMetrics(sessionId, null, false),
        })
      : null,
  }), [sessionDebugMetricsStoreRef, transportRuntimeStoreRef]);

  const sessionInfraRuntime = useMemo(() => createSessionInfraFacadeRuntime({
    stateRef: options.stateRef,
    dispatch: options.dispatch,
    reduceSessionAction,
    transportRuntimeStoreRef,
    sessionBufferStoreRef,
    sessionRenderGateRef,
    sessionHeadStoreRef,
    sessionDebugMetricsStoreRef,
    scheduleStatesRef: options.scheduleStatesRef,
    setScheduleStates: options.setScheduleStates,
    sessionAttachTokensRef,
    pendingSessionTransportOpenIntentsRef,
    activeBodySubscriptionSuppressedRef,
    reconnectRuntimesRef,
      pendingInputTailRefreshRef,
      pendingConnectTailRefreshRef,
    pendingResumeTailRefreshRef,
    sessionPullStateRef,
    lastServerActivityAtRef,
    lastTerminalActivityAtRef,
    staleTransportProbeAtRef,
    lastPongAtRef,
    pingIntervalsRef,
    handshakeTimeoutsRef,
    sessionBufferHeadsRef,
    sessionRevisionResetRef,
    lastHeadRequestAtRef,
    lastSyncRequestAtRef,
    terminalCacheLines: options.terminalCacheLines,
    defaultRows: DEFAULT_TERMINAL_SESSION_VIEWPORT.rows,
    bridgeSettings: options.bridgeSettings,
    wsUrl: options.wsUrl,
    staleActivityMs: ACTIVE_TRANSPORT_STALE_ACTIVITY_MS,
    runtimeDebug,
  }), [options.bridgeSettings, options.dispatch, options.scheduleStatesRef, options.setScheduleStates, options.stateRef, options.terminalCacheLines, options.wsUrl]);

  const {
    readSessionBufferSnapshot,
    updateSessionSync,
    setActiveSessionSync,
    setLiveSessionIdsSync,
    setActiveBodySubscriptionSuppressedSync,
    createSessionSync,
    deleteSessionSync,
    moveSessionSync,
    setSessionTitleSync,
    incrementConnectedSync,
    readSessionTransportResource,
    readSessionTransportSocket,
    readSessionTransportHost,
    readSessionTransportRuntime,
    readSessionTargetRuntime,
    readSessionTargetKey,
    readSessionTargetControlSocket,
    readSessionTargetTerminalSocket,
    readSessionTargetTerminalMuxReady,
    readSessionTerminalChannel,
    readSessionIdForTerminalChannel,
    readOpeningSessionTerminalChannelsForTarget,
    readSessionRequestedTerminalGeometry,
    writeSessionTransportHost,
    writeSessionTransportSocket,
    writeSessionTargetControlSocket,
    writeSessionTargetTerminalSocket,
    writeSessionTargetTerminalMuxReady,
    ensureSessionTerminalChannel,
    writeSessionTerminalChannelState,
    writeSessionRequestedTerminalGeometry,
    moveSessionTransportSocketAside,
    clearSessionTransportRuntime,
    drainSessionSupersededSockets,
    readSessionTransportToken,
    writeSessionTransportToken,
    isSessionTransportActive,
    shouldAcceptSessionLiveBuffer,
    hasPendingSessionTransportOpen,
    isPendingSessionTransportOpenStale,
    isReconnectInFlight,
    resolveSessionCacheLines,
    getSessionRenderBufferSnapshot,
    getSessionBufferStore,
    getSessionRenderBufferStore,
    getSessionHeadStore,
    recordSessionRx,
    recordSessionRxBytesOnly,
    scheduleSessionRenderCommit,
    markPendingInputTailRefresh,
    clearSessionPullState,
    settleSessionPullState,
    resetSessionTransportPullBookkeeping,
    isSessionTransportActivityStale,
    sendSocketPayload,
    buildTraversalSocketForHost,
    applyTransportDiagnostics,
    flushRuntimeDebugLogs,
    setScheduleStateForSession,
    clearHeartbeat,
    clearSessionHandshakeTimeout,
    setSessionHandshakeTimeout,
    clearTailRefreshRuntime,
    startSocketHeartbeat,
  } = sessionInfraRuntime;

  const {
    cleanupControlSocket,
    clearReconnectForSession,
    cleanupSocket,
    scheduleReconnect,
    queueConnectTransportOpenIntent,
    sendTerminalResize,
  } = useMemo(() => createSessionTransportOrchestrationRuntime({
    stateRef: options.stateRef,
    readSessionBufferSnapshot,
    runtimeDebug,
    sessionHandshakeTimeoutMs: SESSION_HANDSHAKE_TIMEOUT_MS,
    sessionTerminalReadyTimeoutMs: SESSION_TERMINAL_READY_TIMEOUT_MS,
    refs: {
      pendingSessionTransportOpenIntentsRef,
      reconnectRuntimesRef,
      manualCloseRef,
      lastPongAtRef,
      lastServerActivityAtRef,
      staleTransportProbeAtRef,
      sessionDebugMetricsStoreRef,
      handleSocketServerMessageRef,
      handleSocketConnectedBaselineRef,
      finalizeSocketFailureBaselineRef,
    },
    readSessionTargetControlSocket,
    readSessionTargetTerminalSocket,
    readSessionTargetTerminalMuxReady,
    readSessionTargetRuntime,
    readSessionTargetKey,
    readSessionTerminalChannel,
    readSessionIdForTerminalChannel,
    readOpeningSessionTerminalChannelsForTarget,
    readSessionTransportSocket,
    readSessionTransportResource,
    readSessionTransportToken,
    readSessionTransportHost,
    writeSessionTransportToken,
    writeSessionTargetControlSocket,
    writeSessionTargetTerminalSocket,
    writeSessionTargetTerminalMuxReady,
    writeSessionTransportSocket,
    ensureSessionTerminalChannel,
    writeSessionTerminalChannelState,
    moveSessionTransportSocketAside,
    drainSessionSupersededSockets,
    updateSessionSync,
    clearHeartbeat,
    clearSessionHandshakeTimeout,
    setSessionHandshakeTimeout,
    clearTailRefreshRuntime,
    clearSessionPullState,
    sendSocketPayload,
    buildTraversalSocketForHost,
    applyTransportDiagnostics,
    recordSessionRx,
    recordControlTransportRxBytes: recordSessionRxBytesOnly,
    flushRuntimeDebugLogs,
    startSocketHeartbeat,
    setScheduleStateForSession,
    writeSessionRequestedTerminalGeometry,
    handleTargetMuxMessage: (payload) => settleSessionTmuxTargetRequestRuntime({
      pendingRequestsRef: tmuxTargetRequestsRef,
      requestId: payload.requestId,
      message: payload.message,
      runtimeDebug,
    }),
    readRequestedTerminalGeometry: (sessionId: string) => {
      const requestedGeometry = readSessionRequestedTerminalGeometry(sessionId);
      if (
        options.bridgeSettings.terminalWidthMode === 'adaptive-phone'
        && requestedGeometry?.widthMode === 'adaptive-phone'
        && Number.isFinite(requestedGeometry.cols)
      ) {
        return requestedGeometry;
      }
      if (options.bridgeSettings.terminalWidthMode === 'adaptive-phone') {
        return {
          widthMode: 'adaptive-phone',
          cols: DEFAULT_TERMINAL_SESSION_VIEWPORT.cols,
        };
      }
      return { widthMode: 'mirror-fixed' };
    },
  }), [
    applyTransportDiagnostics,
    buildTraversalSocketForHost,
    clearHeartbeat,
    clearSessionHandshakeTimeout,
    clearSessionPullState,
    clearTailRefreshRuntime,
    drainSessionSupersededSockets,
    flushRuntimeDebugLogs,
    moveSessionTransportSocketAside,
    options.bridgeSettings.terminalWidthMode,
    options.stateRef,
    readSessionTargetControlSocket,
    readSessionTargetTerminalSocket,
    readSessionTargetTerminalMuxReady,
    readSessionIdForTerminalChannel,
    readSessionTerminalChannel,
    readOpeningSessionTerminalChannelsForTarget,
    readSessionTargetKey,
    readSessionRequestedTerminalGeometry,
    readSessionTargetRuntime,
    readSessionTransportHost,
    readSessionTransportResource,
    readSessionTransportSocket,
    readSessionTransportToken,
    recordSessionRxBytesOnly,
    sendSocketPayload,
    setScheduleStateForSession,
    setSessionHandshakeTimeout,
    startSocketHeartbeat,
    updateSessionSync,
    ensureSessionTerminalChannel,
    writeSessionTargetControlSocket,
    writeSessionTargetTerminalSocket,
    writeSessionTargetTerminalMuxReady,
    writeSessionTerminalChannelState,
    writeSessionRequestedTerminalGeometry,
    writeSessionTransportSocket,
    writeSessionTransportToken,
  ]);

  const sessionMessageRuntime: SessionMessageAssembliesResult = useMemo(() => createSessionMessageAssemblies({
    stateRef: options.stateRef,
    scheduleStatesRef: options.scheduleStatesRef,
    sessionVisibleRangeRef,
    sessionBufferHeadsRef,
    sessionPullStateRef,
    sessionRevisionResetRef,
    sessionBufferStoreRef,
    sessionHeadStoreRef,
    sessionDebugMetricsStoreRef,
    lastSyncRequestAtRef,
    lastHeadRequestAtRef,
    staleTransportProbeAtRef,
    lastPongAtRef,
    lastConnectedBaselineAtRef,
    connectedBaselineBurstGuardRef,
    pendingInputTailRefreshRef,
    pendingConnectTailRefreshRef,
    pendingResumeTailRefreshRef,
    pendingSessionTransportOpenIntentsRef,
    manualCloseRef,
    fileTransferMessageRuntimeRef,
    remoteWindowMessageRuntimeRef,
    readSessionTransportSocket,
    readSessionTransportResource,
    readSessionBufferSnapshot,
    sendSocketPayload,
    clearSessionPullState,
    settleSessionPullState,
    scheduleSessionRenderCommit,
    isSessionTransportActive,
    shouldAcceptSessionLiveBuffer,
    resolveSessionCacheLines,
    resolveTerminalRefreshCadence: resolveSessionTerminalRefreshCadence,
    setScheduleStateForSession,
    setSessionTitleSync,
    updateSessionSync,
    writeSessionTransportToken,
    cleanupSocket,
    applyTransportDiagnostics,
    incrementConnectedSync,
  }), [
    applyTransportDiagnostics,
    cleanupSocket,
    clearSessionPullState,
    connectedBaselineBurstGuardRef,
    fileTransferMessageRuntimeRef,
    remoteWindowMessageRuntimeRef,
    incrementConnectedSync,
    isSessionTransportActive,
    lastConnectedBaselineAtRef,
    lastHeadRequestAtRef,
    staleTransportProbeAtRef,
    lastPongAtRef,
    lastSyncRequestAtRef,
    manualCloseRef,
    options.scheduleStatesRef,
    options.stateRef,
    pendingConnectTailRefreshRef,
    pendingInputTailRefreshRef,
    pendingResumeTailRefreshRef,
    pendingSessionTransportOpenIntentsRef,
    readSessionBufferSnapshot,
    readSessionTransportResource,
    readSessionTransportSocket,
    resolveSessionCacheLines,
    resolveSessionTerminalRefreshCadence,
    scheduleSessionRenderCommit,
    sendSocketPayload,
    sessionBufferHeadsRef,
    sessionBufferStoreRef,
    sessionDebugMetricsStoreRef,
    sessionHeadStoreRef,
    sessionPullStateRef,
    sessionRevisionResetRef,
    sessionVisibleRangeRef,
    setScheduleStateForSession,
    settleSessionPullState,
    setSessionTitleSync,
    updateSessionSync,
    writeSessionTransportToken,
  ]);

  const {
    requestSessionBufferSync,
    requestSessionBufferHead,
    handleSocketServerMessage,
    handleSocketConnectedBaseline,
    finalizeSocketFailureBaseline,
  } = sessionMessageRuntime;
  handleSocketServerMessageRef.current = handleSocketServerMessage;
  handleSocketConnectedBaselineRef.current = handleSocketConnectedBaseline;
  finalizeSocketFailureBaselineRef.current = finalizeSocketFailureBaseline;

  return useMemo(() => ({
    getSessionRenderBufferSnapshot,
    getSessionBufferStore,
    getSessionRenderBufferStore,
    getSessionHeadStore,
    flushRuntimeDebugLogs,
    clearReconnectForSession,
    writeSessionTransportHost,
    writeSessionTransportToken,
    scheduleReconnect,
    readSessionBufferSnapshot,
    setActiveSessionSync,
    setLiveSessionIdsSync,
    setActiveBodySubscriptionSuppressedSync,
    createSessionSync,
    deleteSessionSync,
    moveSessionSync,
    updateSessionSync,
    setSessionTitleSync,
    isSessionTransportActive,
    shouldAcceptSessionLiveBuffer,
    hasPendingSessionTransportOpen,
    isPendingSessionTransportOpenStale,
    isReconnectInFlight,
    resolveSessionCacheLines,
    scheduleSessionRenderCommit,
    markPendingInputTailRefresh,
    resetSessionTransportPullBookkeeping,
    isSessionTransportActivityStale,
    sendSocketPayload,
    setScheduleStateForSession,
    clearSessionHandshakeTimeout,
    cleanupControlSocket,
    cleanupSocket,
    queueConnectTransportOpenIntent,
    sendTerminalResize,
    readSessionTransportResource,
    readSessionTransportSocket,
    readSessionTransportHost,
    readSessionTransportRuntime,
    readSessionTargetRuntime,
    readSessionTerminalChannel,
    readSessionTargetKey,
    readSessionRequestedTerminalGeometry,
    writeSessionRequestedTerminalGeometry,
    clearSessionTransportRuntime,
    requestSessionBufferSync,
    requestSessionBufferHead,
    resolveTerminalRefreshCadence: resolveSessionTerminalRefreshCadence,
  }), [
    clearReconnectForSession,
    clearSessionHandshakeTimeout,
    cleanupControlSocket,
    cleanupSocket,
    createSessionSync,
    deleteSessionSync,
    flushRuntimeDebugLogs,
    getSessionBufferStore,
    getSessionHeadStore,
    getSessionRenderBufferSnapshot,
    getSessionRenderBufferStore,
    hasPendingSessionTransportOpen,
    isPendingSessionTransportOpenStale,
    isReconnectInFlight,
    isSessionTransportActive,
    shouldAcceptSessionLiveBuffer,
    isSessionTransportActivityStale,
    markPendingInputTailRefresh,
    moveSessionSync,
    queueConnectTransportOpenIntent,
    sendTerminalResize,
    readSessionBufferSnapshot,
    readSessionTargetKey,
    readSessionTargetRuntime,
    readSessionTerminalChannel,
    readSessionTransportHost,
    readSessionTransportResource,
    readSessionTransportRuntime,
    readSessionTransportSocket,
    requestSessionBufferHead,
    requestSessionBufferSync,
    resetSessionTransportPullBookkeeping,
    resolveSessionCacheLines,
    resolveSessionTerminalRefreshCadence,
    scheduleReconnect,
    scheduleSessionRenderCommit,
    sendSocketPayload,
    setActiveSessionSync,
    setScheduleStateForSession,
    setSessionTitleSync,
    updateSessionSync,
    writeSessionTransportHost,
    writeSessionTransportToken,
  ]);
}
